#!/usr/bin/env bash
#
# ArtBloom — one-shot ECS bootstrap.
# Idempotent: re-run any time to repair a broken host.
#
# Usage (from the ECS VM, as root):
#
#   curl -fsSL https://raw.githubusercontent.com/ShadowsKuming/art_edu/main/deploy/ecs/bootstrap.sh \
#     | ARK_API_KEY="ark-xxx" \
#       DOMAIN="api.artbloomedu.com" \
#       TEXTBOOK_ASSETS_URL="https://pub-xxx.r2.dev" \
#       bash
#
# Required env vars:
#   ARK_API_KEY            — Volcengine Ark LLM key
#   DOMAIN                 — public hostname for Caddy (e.g. api.artbloomedu.com)
#   TEXTBOOK_ASSETS_URL    — R2 public bucket URL (e.g. https://pub-xxx.r2.dev)
#
# Optional env vars:
#   CORS_ALLOW_ORIGINS         — defaults to "*"
#   ARK_STORY_MODEL            — defaults handled by main.py
#   ARK_CHAT_MODEL             — ditto
#   ARK_VIDEO_MODEL            — ditto
#   ARK_IMAGE_MODEL            — ditto
#   VOLCENGINE_SPEECH_API_KEY  — unused today, stored for future TTS port
#   REPO                       — defaults to canonical repo URL
#   BRANCH                     — defaults to main
#   INSTALL_DIR                — defaults to /opt/artbloom
#   SERVICE_USER               — defaults to artbloom

set -euo pipefail

REPO="${REPO:-https://github.com/ShadowsKuming/art_edu.git}"
BRANCH="${BRANCH:-main}"
INSTALL_DIR="${INSTALL_DIR:-/opt/artbloom}"
SERVICE_USER="${SERVICE_USER:-artbloom}"
CORS_ALLOW_ORIGINS="${CORS_ALLOW_ORIGINS:-*}"

# ── Pre-flight ──────────────────────────────────────────────────────

if [[ $EUID -ne 0 ]]; then
    echo "ERROR: bootstrap.sh must run as root (sudo bash …)" >&2
    exit 1
fi

for var in ARK_API_KEY DOMAIN TEXTBOOK_ASSETS_URL; do
    if [[ -z "${!var:-}" ]]; then
        echo "ERROR: required env var '$var' is empty" >&2
        exit 1
    fi
done

echo "==> ArtBloom bootstrap"
echo "    REPO          = $REPO"
echo "    BRANCH        = $BRANCH"
echo "    INSTALL_DIR   = $INSTALL_DIR"
echo "    SERVICE_USER  = $SERVICE_USER"
echo "    DOMAIN        = $DOMAIN"
echo

# ── System packages ─────────────────────────────────────────────────

echo "==> apt update + base packages"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
    python3 python3-venv python3-pip git curl ca-certificates \
    debian-keyring debian-archive-keyring apt-transport-https gnupg

# ── Caddy (official repo, latest stable) ────────────────────────────

if ! command -v caddy >/dev/null 2>&1; then
    echo "==> installing Caddy"
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' \
        | gpg --dearmor -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
    curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' \
        > /etc/apt/sources.list.d/caddy-stable.list
    apt-get update -qq
    apt-get install -y -qq caddy
else
    echo "==> Caddy already installed ($(caddy version | head -1))"
fi

# ── Service user ────────────────────────────────────────────────────

if ! id "$SERVICE_USER" &>/dev/null; then
    echo "==> creating service user '$SERVICE_USER'"
    useradd --system --create-home --shell /bin/bash "$SERVICE_USER"
fi

# ── Repo clone / update ─────────────────────────────────────────────

if [[ -d "$INSTALL_DIR/.git" ]]; then
    echo "==> updating existing checkout at $INSTALL_DIR"
    git -C "$INSTALL_DIR" fetch --quiet origin "$BRANCH"
    git -C "$INSTALL_DIR" reset --quiet --hard "origin/$BRANCH"
else
    echo "==> cloning $REPO ($BRANCH) → $INSTALL_DIR"
    git clone --quiet --branch "$BRANCH" "$REPO" "$INSTALL_DIR"
fi
chown -R "$SERVICE_USER:$SERVICE_USER" "$INSTALL_DIR"

# Allow root's cron deploy.sh to git-fetch without "dubious ownership" warning
git config --global --add safe.directory "$INSTALL_DIR"

# ── Python venv + requirements ──────────────────────────────────────

echo "==> creating venv + installing requirements"
sudo -u "$SERVICE_USER" bash -lc "
    set -e
    cd '$INSTALL_DIR'
    test -d .venv || python3 -m venv .venv
    .venv/bin/pip install --quiet --upgrade pip
    .venv/bin/pip install --quiet -r backend/requirements.txt
"

# ── Backend .env ────────────────────────────────────────────────────

echo "==> writing $INSTALL_DIR/backend/.env"
ENV_FILE="$INSTALL_DIR/backend/.env"
{
    echo "# Generated by deploy/ecs/bootstrap.sh — do not commit"
    echo "ARK_API_KEY=$ARK_API_KEY"
    echo "CORS_ALLOW_ORIGINS=$CORS_ALLOW_ORIGINS"
    echo "TEXTBOOK_ASSETS_URL=$TEXTBOOK_ASSETS_URL"
    [[ -n "${ARK_STORY_MODEL:-}" ]]           && echo "ARK_STORY_MODEL=$ARK_STORY_MODEL"
    [[ -n "${ARK_CHAT_MODEL:-}" ]]            && echo "ARK_CHAT_MODEL=$ARK_CHAT_MODEL"
    [[ -n "${ARK_VIDEO_MODEL:-}" ]]           && echo "ARK_VIDEO_MODEL=$ARK_VIDEO_MODEL"
    [[ -n "${ARK_IMAGE_MODEL:-}" ]]           && echo "ARK_IMAGE_MODEL=$ARK_IMAGE_MODEL"
    [[ -n "${VOLCENGINE_SPEECH_API_KEY:-}" ]] && echo "VOLCENGINE_SPEECH_API_KEY=$VOLCENGINE_SPEECH_API_KEY"
} > "$ENV_FILE"
chown "$SERVICE_USER:$SERVICE_USER" "$ENV_FILE"
chmod 600 "$ENV_FILE"

# ── systemd unit ────────────────────────────────────────────────────

echo "==> writing /etc/systemd/system/artbloom-api.service"
sed -e "s|__INSTALL_DIR__|$INSTALL_DIR|g" \
    -e "s|__USER__|$SERVICE_USER|g" \
    "$INSTALL_DIR/deploy/ecs/artbloom-api.service" \
    > /etc/systemd/system/artbloom-api.service

# ── Caddyfile ───────────────────────────────────────────────────────

echo "==> writing /etc/caddy/Caddyfile"
sed -e "s|__DOMAIN__|$DOMAIN|g" \
    "$INSTALL_DIR/deploy/ecs/Caddyfile" \
    > /etc/caddy/Caddyfile

# ── Enable + (re)start ──────────────────────────────────────────────

echo "==> reloading systemd + starting services"
systemctl daemon-reload
systemctl enable --now artbloom-api.service
systemctl restart artbloom-api.service

# `caddy reload` is graceful (no downtime); falls back to restart if Caddy is fresh.
systemctl enable --now caddy.service
caddy reload --config /etc/caddy/Caddyfile --force 2>/dev/null \
    || systemctl restart caddy.service

# ── Cron auto-deploy (every 5 minutes) ──────────────────────────────

echo "==> installing 5-min auto-deploy cron"
CRON_LINE="*/5 * * * * $INSTALL_DIR/deploy/ecs/deploy.sh >> /var/log/artbloom-deploy.log 2>&1"
( crontab -l 2>/dev/null | grep -v 'artbloom/deploy/ecs/deploy.sh' || true ; echo "$CRON_LINE" ) | crontab -
touch /var/log/artbloom-deploy.log
chmod 644 /var/log/artbloom-deploy.log

# ── Final smoke test ────────────────────────────────────────────────

echo
echo "============================================================"
echo "  ✓ bootstrap complete"
echo
echo "  service status :  systemctl status artbloom-api caddy"
echo "  service logs   :  journalctl -u artbloom-api -f"
echo "  caddy logs     :  journalctl -u caddy -f"
echo "  deploy log     :  tail -f /var/log/artbloom-deploy.log"
echo
echo "  smoke test (give Caddy ~30s to fetch the cert first):"
echo "    curl -s https://$DOMAIN/health | jq ."
echo "============================================================"
